version: '3.11'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - proxy-net

  web:
    image: proxy
    container_name: fastapi
    ports:
      - "8000:8000"
    networks:
      - proxy-net
    depends_on:
      - redis
      - celery_worker
    volumes:
      - ./uploadedFiles:/app/uploadedFiles

  celery_worker:
    image: celery
    container_name: celery
    networks:
      - proxy-net
    depends_on:
      - redis
    volumes:
      - ./uploadedFiles:/app/uploadedFiles
  
networks:
  proxy-net:
    external: true