apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxy-claim
spec:
  accessModes:
  - ReadWriteOnce   # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: azuredisk-standard-retain
  resources:
    requests:
      storage: 100Gi